.\" Copyright (C) 2015 Riccardo Boninsegna <rboninsegna2@gmail.com>
.TH gummiboot 5 "2015-6-17" "48-100" "gummiboot-nomachineid"
.SH NAME
/etc/default/gummiboot - Settings for
.BR update-gummiboot (8)
.SH SYNOPSIS
.B $EDITOR
.I /etc/default/gummiboot
.SH DESCRIPTION

.I /etc/default/gummiboot
is a shell script which is automatically included in
.BR update-gummiboot (8)
to override its default settings.

.SH FORMAT

.B GUMMIBOOT_EFI=
.RS
Sets mount point of EFI system partition.
Defaults to
.IR "/boot/efi" .
.RE

.B GUMMIBOOT_ROOT=
.RS
Sets the root partition of your GNU/Linux system.
Defaults to
.IR "an empty string" ,
which makes
.B update-gummiboot
parse
.I /etc/fstab
for it.
.RE

.B GUMMIBOOT_OPTIONS=
.RS
Sets arbitrary kernel arguments, that will supplement
.B initrd=
and
.B root=
.
Defaults to
.IR "ro quiet" .
.RE

.SH SEE ALSO
.BR update-gummiboot (8)

.SH AUTHOR
.I /etc/default/gummiboot
has been invented by Julian Andres Klode while porting gummiboot to the Debian project.

Manpage written by Riccardo Boninsegna.
