#!/bin/sh
# postinst script for gummiboot

set -e

# Upgrade from gummiboot
if [ -e /etc/default/gummiboot ]; then
    mv -f /etc/default/gummiboot /etc/default/gummiboot-nomachineid
fi

. /etc/default/gummiboot-nomachineid

if [ "$1" = "configure" -a "$2" = "" ]; then
    for kernel in /boot/vmlinuz-*; do
        update-gummiboot $(echo $kernel | cut -f2- -d-)
    done
fi

if [ "$1" = "configure" ]; then
    gummiboot update --path="$GUMMIBOOT_EFI" || :
fi

#DEBHELPER#
